spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 10000
        connection:
          autocommit: true

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:data/rs.db
    username: sa
    password: sa
management:
  endpoints:
    web:
      exposure:
        include: 'health,info,mappings'

# not ready for Spring Boot 3:
#springdoc:
#  api-docs:
#    path: /api-docs

server:
  port: 8081

logging:
  level:
    root: info
    org:
      hibernate: warn
    com:
     dewarim: debug

